import colors from "../../../constants/colors";

export default {
    navigationTintColor: colors.orange,
    navigationTitleColor: colors.superLightBlueGrey,
    confirmationButtonColor: colors.orange,
    confirmationButtonTextColor: colors.white,
    confirmationButtonIconColor: colors.white,
    cancelButtonColor: colors.lightBlueGrey,
    cancelButtonTextColor: colors.white,
    cancelButtonIconColor: colors.white,
    disabledButtonColor: colors.lightGrey,
    disabledButtonTextColor: colors.grey,
    disabledButtonIconColor: colors.grey,
    disabledButtonBorderColor: colors.grey,
    neutralButtonColor: colors.white,
    neutralButtonTextColor: colors.darkBlueGrey,
    neutralButtonIconColor: colors.orange,
    clearButtonTextColor: colors.blueGrey,
    screenBackgroundColor: colors.lightGrey,
    textFieldTitleColor: colors.darkBlueGrey,
    textFieldValueColor: colors.lightBlueGrey,
    textFieldErrorColor: colors.red,
    textFieldSelectionColor: colors.orange,
    titleTextColor: colors.darkBlueGrey,
    descriptionTextColor: colors.blueGrey,
    titleTextDisableColor: colors.superLightBlueGrey,
    descriptionTextDisabledColor: colors.superLightBlueGrey,
    progressBarBaseColor: colors.lightGrey,
    homeHeaderTopColor: colors.yellow,
    homeHeaderBottomColor: colors.darkYellow,
    streakSlotColor: colors.opaqueYellow,
    streakButtonCompleted: colors.orange,
    streakButtonIconCompleted: colors.white,
    streakButtonToday: colors.white,
    streakButtonIconToday: colors.extraLightBlueGrey,
    streakCompletedCheck: colors.orange,
    exerciseCardHighlightedShadowColor: colors.orange,
    exerciseCardCompletedCheck: colors.lightGreen,
    exerciseCardMoodFaceIconColor: colors.lightGreen,
    exerciseCardSatisfiedFaceIconColor: colors.yellow,
    exerciseCardNotVerySatisfiedFaceIconColor: colors.lightRed,
    viewWhiteBackground : colors.white
}